resolver: lts-5.7
packages:
  - '.'
  - location:
      git: https://github.com/futurice/haskell-base64-bytestring-type.git
      commit: 0a1176d16c71c219fe113bc3f130f64d8dda47bc
extra-deps:
  - servant-0.5
  - servant-server-0.5
  - servant-client-0.5
  - servant-lucid-0.5
  - refined-0.1.2

